---
- name: Install shell packages
  ansible.builtin.apt:
    pkg: "{{ user_shell_packages }}"

- name: Set root password
  ansible.builtin.user:
    name: "root"
    password: "{{ root_password_hash }}"
  when: root_password_hash != ""

- name: Create groups
  ansible.builtin.include_tasks:
    file: create-group.yml
  loop: "{{ user_groups }}"
  loop_control:
    label: "{{ item.name }}"

- name: Create users
  ansible.builtin.include_tasks:
    file: create-user.yml
  loop: "{{ users }}"
  loop_control:
    label: "{{ item.username }}"
